env:
  browser: true
  es2021: true
extends:
  - 'plugin:svelte/prettier'
parser: '@typescript-eslint/parser'
parserOptions:
  project: 'tsconfig.json'
  extraFileExtensions: ['.svelte']
  ecmaVersion: latest
  sourceType: module
rules: {}
overrides:
   - files: ['*.svelte']
     parser: 'svelte-eslint-parser'
      # // Parse the `<script>` in `.svelte` as TypeScript by adding the following configuration.
     parserOptions:
        parser: '@typescript-eslint/parser'

