name: links_hinten_deploy

on:
    push:
        branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v2
    - name: Set up kubectl
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: get pods

    - name: Deploy
      uses: Azure/k8s-deploy@v4
      with:
        namespace: 'links-hinten'
        manifests: |
          deploy/tic-tac-toe.deploy.yml
        images: 'ghcr.io/ci-cd-2024-dhbw-hdh/links-hinten:main'
    
    - name: Set imagePullSecret
      uses: azure/k8s-create-secret@v4
      with:
        namespace: 'gruppe-gaming'
        secret-name: 'regcred'
        container-registry-url: 'ghcr.io'
        container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
        container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
      id: create-secret

    - name: Verify deployment
      uses: actions-hub/kubectl@master
      with:
        args: rollout status deployment/tic-tac-toe
