name: links_hinten_deploy

on:
    push:
        branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v2
    - uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
    #- name: set secret
    #  run: doctl kubectl create secret docker-registry regcred --docker-server=${{ env.REGISTRY }} --docker-username=${{ github.actor }} --docker-password=${{ secrets.GITHUB_TOKEN }}
    - name: deploy
      uses: actions-hub/kubectl@master
      with:
        args: apply -f ${{ github.workspace }}/deploy/tic-tac-toe.deploy.yml

    - name: Verify deployment
      uses: actions-hub/kubectl@master
      with:
        args: rollout status deployment/tic-tac-toe
