name: links_hinten_deploy

on:
    push:
        branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v2
    - uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: get pods
    #- name: set secret
    #  run: doctl kubectl create secret docker-registry regcred --docker-server=${{ env.REGISTRY }} --docker-username=${{ github.actor }} --docker-password=${{ secrets.GITHUB_TOKEN }}
    - name: deploy
      run: kubectl apply -f $GITHUB_WORKSPACE/deploy/tic-tack-toe.deploy.yml
    - name: Verify deployment
      run: kubectl rollout status deployment/tic-tack-toe